import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import RoleProvider from "./RoleProvider";
import Header from "@/components/Header";
import ConditionalBackButton from "@/components/ConditionalBackButton"; // Import the new component

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`bg-gray-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Provider>
					<RoleProvider>
						<Header />
						<div className="container mx-auto p-8 pt-6">
							<ConditionalBackButton />{" "}
							{/* Use the conditional button */}
							{children}
						</div>
					</RoleProvider>
				</Provider>
			</body>
		</html>
	);
}
